### ISSUE TITLE
On Ubuntu Wily 15.10, pritunl-client and pritunl-client-gtk conflict

### ISSUE THREAD

**Issue by gtaylor** [pritunl/pritunl-client-electron#12]
After installation, I restarted and got this error:

![image](https://cloud.githubusercontent.com/assets/75556/10746665/803e20e0-7c0a-11e5-8826-919fee5912e1.png)

**Comment by zachhuff386** [comment]
This was an issue with the build system leaving out the conflicts in debian packages allowing both pritunl-client and pritunl-client-gtk to be installed. It will be fixed in the next release. To fix the error remove pritunl-client and pritunl-client-gtk then install only one of the packages. The pritunl-client-gtk is for desktops, pritunl-client is for servers.
